media:
  input: public/images
  output: /images

content:
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    filename: "{title}.md"

    view:
      primary: title
      fields:
        - title
        - year
        - featured

    fields:
      - name: title
        label: Project title
        type: string
        required: true

      - name: description
        label: Short description
        type: text

      - name: coverImage
        label: Cover image
        type: image

      - name: year
        label: Year
        type: string

      - name: role
        label: Role
        type: string

      - name: tags
        label: Tags
        type: string
        list: true

      - name: featured
        label: Featured project
        type: boolean
        default: false

      - name: body
        label: Case study
        type: rich-text
